---
- hosts: linode
  # if a non-root user hasn't been created when installing, run ansible-playbooks with "--user root --ask-pass" (sshpass needs to be installed on the control machine)
  # otherwise, run "ansible-playbooks with --ask-become-pass" and uncomment the next line
  become: yes

  vars_prompt:
    - name: "client_ready"
      prompt: "Confirm you've successfully installed and configured OpenVPN on the client machine (Y/N)"
      private: no

  roles:
    - role: centos8.openvpn
      when: client_ready == "Y"
...
