---
- name: create directories needed by vim-plug
  file:
    path: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload/"
    state: directory
    register: created_dir
  become: no
  listen: "install vim-plug"

- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ created_dir.path }}/plug.vim"
  become: no
  listen: "install vim-plug"
...
