---
- name: create a directory for OpenVPN
  file:
    path: "{{ openvpn_client_dir }}"
    state: directory

- name: transfer client config file to OpenVPN directory
  template:
    src: client.conf.j2
    dest: "{{ openvpn_client_dir }}/client.conf"
...
