---
# execute "netlify deploy --prod" from the production folder of the maintenance site (do this only once)
# go to the admin URL and add all domains / subdomains that you want to point to the maintenance site

- include_tasks: update_dns_records.yml
  vars:
    record_zone: jagdcake.com
    record_name: "{{ item }}"
    record_type: A
    record_value: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    record_state: absent
  loop:
    - request
    - modeling

- include_tasks: update_dns_records.yml
  vars:
    record_zone: jagdcake.com
    record_name: "{{ item }}"
    record_type: CNAME
    record_value: "{{ netlify_subdomain }}"
    record_state: present
  loop:
    - request
    - modeling

- name: stop docker containers
  docker_compose:
    project_src: "/home/{{ lookup('env', 'USER') }}/Containers/{{ item }}/"
    state: absent
  loop:
    - request
    - modeling

- import_tasks: ../../centos7.set_up/tasks/upgrade_packages.yml
  notify: "reboot the server"

- meta: flush_handlers

- name: start docker containers
  docker_compose:
    project_src: "/home/{{ lookup('env', 'USER') }}/Containers/{{ item }}/"
    state: present
  loop:
    - nginx-proxy
    - request
    - modeling

- pause: # noqa 502
    prompt: "Check if the sites are up"

- include_tasks: update_dns_records.yml
  vars:
    record_zone: jagdcake.com
    record_name: "{{ item }}"
    record_type: CNAME
    record_value: "{{ netlify_subdomain }}"
    record_state: absent
  loop:
    - request
    - modeling

- include_tasks: update_dns_records.yml
  vars:
    record_zone: jagdcake.com
    record_name: "{{ item }}"
    record_type: A
    record_value: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    record_state: present
  loop:
    - request
    - modeling
...
