---
- name: remove unnecessary default packages
  command: eopkg rm "{{ item }}"
  loop:
    - thunderbird
    - libreoffice-common
    - gnome-mpv
    - hexchat
    - rhythmbox

- name: update stable repository
  command: eopkg ur
...
