---
- name: remove unnecessary default packages
  command: eopkg rm "{{ item }}"
  with_items: "{{ items_to_remove }}"

- name: update stable repository
  command: eopkg ur

- name: upgrade all installed packages
  command: eopkg up

- name: install system packages
  command: eopkg it "{{ item }}"
  with_items: "{{ system }}"
...
