---
- name: remove unnecessary default packages
  command: eopkg rm "{{ item }}"
  with_items: "{{ items_to_remove }}"

- name: update stable repository
  command: eopkg ur

- name: upgrade all installed packages
  command: eopkg up

- name: install system packages
  command: eopkg it -y "{{ item }}"
  with_items: "{{ system }}"

- name: install base development tools
  command: eopkg it -c system.devel

- name: install work tools
  command: eopkg it -y "{{ item }}"
  with_items: "{{ tools }}"

- name: install media apps
  command: eopkg it -y "{{ item }}"
  with_items: "{{ media }}"

- name: install python packages
  command: pip3 install --user "{{ item }}"
  with_items: "{{ python }}"
  become: no

- name: install Node.js packages
  command: npm install -g "{{ item }}"
  with_items: "{{ nodejs }}"
  become: no

- name: install Haskell
  pause:
    prompt: https://docs.haskellstack.org/en/stable/README/

- name: update stack package index
  command: stack update
  become: no

- name: install Haskell libraries
  command: stack install --resolver=lts "{{ item }}"
  with_items: "{{ haskell }}"
  become: no

- name: install Ruby gems
  command: gem install "{{ item }}"
  with_items: "{{ ruby }}"
  become: no
...
