---
- name: remove unnecessary default packages
  command: eopkg rm "{{ item }}"
  loop:
    - thunderbird
    - libreoffice-common
    - gnome-mpv
    - hexchat
    - rhythmbox

- name: update stable repository
  command: eopkg ur

- name: upgrade all installed packages
  command: eopkg up

- name: install system packages
  command: eopkg it "{{ item }}"
  loop:
    - terminator
    - keepassx
    - veracrypt
    - pigz
    - p7zip
    - etcher
    - exa
    - ripgrep
    - fd
    - bat
    - rclone
    - restic
    - lightdm-settings
    - dmenu
    - psensor
    - smartmontools
    - yaru-gtk-theme
    - la-capitaine-icon-theme
    - w3m
    - nmap
    - glances
...
