---
- name: remove unnecessary default packages
  command: eopkg rm "{{ item }}"
  with_items: "{{ items_to_remove }}"

- name: update stable repository
  command: eopkg ur

- name: upgrade all installed packages
  command: eopkg up

- name: install system packages
  command: eopkg it "{{ item }}"
  with_items: "{{ system }}"

- name: install base development tools
  command: eopkg it -c system.devel

- name: install work tools
  command: eopkg it "{{ item }}"
  with_items: "{{ tools }}"

- name: install media apps
  command: eopkg it "{{ item }}"
  with_items: "{{ media }}"
...
