---
- import_tasks: create_user.yml
- import_tasks: set_up_ssh.yml
  tags:
    - ssh
    - security
- import_tasks: ssh_security.yml
  tags:
    - ssh
    - security
- import_tasks: set_up_firewalld.yml
  tags: security
- import_tasks: upgrade_packages.yml
  tags: upgrade_packages
- import_tasks: set_up_fail2ban.yml
  tags:
    - fail2ban
    - security
- import_tasks: change_dns.yml
- name: reboot the server
  reboot:
...
