---
- name: make sure firewalld is running and enabled
  service:
    name: firewalld
    state: started
    enabled: yes

- name: remove SSH access from the public zone
  firewalld:
    service: ssh
    zone: public
    state: disabled
    permanent: yes
  notify: "reload firewalld"

- name: allow access to SSH only from my IP
  firewalld:
    source: "{{ static_ip }}"
    zone: dmz
    state: enabled
    permanent: yes
  notify: "reload firewalld"

- name: drop (no rejection reply) all non-whitelisted connections to the SSH service
  command: "firewall-cmd --zone=public --set-target=DROP --permanent"
  notify: "reload firewalld"

- name: restore the ability to ping (broken by the previous task)
  firewalld:
    zone: dmz
    rich_rule: 'rule protocol value="icmp" accept'
    state: enabled
    permanent: yes
  notify: "reload firewalld"

- name: allow HTTP traffic
  firewalld:
    zone: public
    service: http
    state: enabled
    permanent: yes
  notify: "reload firewalld"

- name: allow HTTPS traffic
  firewalld:
    zone: public
    service: https
    state: enabled
    permanent: yes
  notify: "reload firewalld"
...
