---
# Source: https://infosec.mozilla.org/guidelines/openssh

- name: update SSH config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: "reload sshd"

- name: deactivate short moduli
  shell: awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.tmp && mv /etc/ssh/moduli.tmp /etc/ssh/moduli
...
