---
- hosts: localhost
  roles:
    - site.static.production.set_up

  vars:
    git_repo: ~/Documents/web_dev/1_templates/static_site/
    project_dir: ~/Documents/web_dev/3_my_sites/data/website/public/
