---
- name: install release package "Extra Packages for Enterprise Linux"
  yum:
    name: epel-release
    state: present

- name: install docker
  yum:
    name:
      - docker
      - docker-compose
    state: present

- name: start docker
  service:
    name: docker
    state: started
    enabled: yes

# Source: https://coderleaf.wordpress.com/2017/02/10/run-docker-as-user-on-centos7/
- name: add user to the docker group
  user:
    name: "{{ username }}"
    append: yes
    groups: dockerroot

- name: change ownership of the docker daemon socket
  lineinfile:
    path: /etc/docker/daemon.json
    # replace the empty object
    regexp: '{}'
    line: '{ "live-restore": true, "group": "dockerroot" }'
    state: present
    # don't add the line if the regexp doesn't match
    backrefs: yes
    create: yes
  register: the_file_was

- name: restart docker # noqa 503
  service:
    name: docker
    state: restarted
  when: the_file_was.changed

- name: reset SSH connection to make sure docker error was successfully fixed
  meta: reset_connection
...
