---
- name: disallow root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "#PermitRootLogin yes"
    line: "PermitRootLogin no"
    state: present
    # with backrefs — doesn't add the line if the regex doesn't match anything
    backrefs: yes
  notify: "reload sshd"

- name: disallow password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "PasswordAuthentication yes"
    line: "PasswordAuthentication no"
    state: present
    backrefs: yes
  notify: "reload sshd"

- name: allow only the specified user to login
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "AllowUsers {{ username }}"
    state: present
    insertafter: EOF
  notify: "reload sshd"
...
