---
# the archive module can only be used on the local machine
# still have to run ansible-playbooks with --ask-become-pass
- hosts: localhost

  vars_prompt:
  - name: "local_project_dir"
    prompt: enter path to project directory
    private: no
    confirm: yes

  tasks:
  - name: register project directory variable
    set_fact: "local_project_dir={{ local_project_dir }}"

  - name: archive project files and directories
    archive:
      # removing the wildcard from path makes it so that node_modules doesn't get excluded
      path: "{{ local_project_dir }}/*"
      dest: "{{ local_project_dir }}/project_files.tar.gz"
      # Wait for merge https://github.com/ansible/ansible/pull/34659
      # Source: https://github.com/ansible/ansible/issues/34316
      exclude_path:
      # directories are excluded only if there is no trailing slash,
      # a nested directory (itself) is never excluded, trailing slash or no, but files inside of it are, directories aren't
      - "{{ local_project_dir }}/docker_volumes/data/"
      - "{{ local_project_dir }}/node_modules"
      - "{{ local_project_dir }}/TODO"

- hosts: vultr
  become: yes

  vars:
    remote_projects_dir: "/home/{{ lookup('env', 'USER') }}/Containers/"

  vars_prompt:
  - name: "project_name"
    prompt: enter project name
    private: no
    confirm: yes

  tasks:
  - name: create a directory for the project on the server
    file:
      path: "{{ remote_projects_dir }}/{{ project_name }}"
      state: directory
      owner: "{{ lookup('env', 'USER') }}"
      group: "{{ lookup('env', 'USER') }}"

  - name: unarchive files on the server
    unarchive:
      src: "{{ hostvars.localhost.local_project_dir }}/project_files.tar.gz"
      dest: "{{ remote_projects_dir }}/{{ project_name }}/"
      # owner and group of all directories (only) is root
      owner: "{{ lookup('env', 'USER') }}"
      group: "{{ lookup('env', 'USER') }}"
...
