---
- name: install docker
  yum:
    name:
      - docker
      - docker-compose
    state: present

- name: prevent docker-compose permission error
  file:
    dest: /var/run/docker.sock
    owner: "{{ username }}"

- name: start docker
  service:
    name: docker
    state: started
    enabled: yes
...
