---
- name: install release package "Extra Packages for Enterprise Linux"
  yum:
    name: epel-release
    state: present

- name: install fail2ban
  yum:
    name: fail2ban
    state: present

- name: start fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: update fail2ban config
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local

- name: create jail log file # shouldn't have to
  file:
    path: /var/log/auth.log
    state: touch

# TODO Enhancement:
# reload only if the config file has changed
- name: reload fail2ban
  service:
    name: fail2ban
    state: reloaded
...
