---
- name: install release package "Extra Packages for Enterprise Linux"
  yum:
    name: epel-release
    state: present

- name: install docker
  yum:
    name:
      - docker
      - docker-compose
    state: present

- name: start docker
  service:
    name: docker
    state: started
    enabled: yes

# TODO Fix:
# docker.sock's owner didn't change?
- name: prevent docker-compose permission error
  file:
    dest: /var/run/docker.sock
    owner: "{{ username }}"
...
