---
- name: install fail2ban
  yum:
    name: fail2ban
    state: present

- name: start fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: update fail2ban config
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/

- name: reload fail2ban
  service:
    name: fail2ban
    state: reloaded
...
