---
- name: generate certificate request
  expect:
    command: ./easyrsa gen-req "{{ server_entity_name }}"
    responses:
      # note that some of the prompts don't end with whitespace
      # could be changed in a future version
      .*Enter\sPEM\spass.*:$: "{{ pem_passphrase }}"
      .*Verifying.*\sphrase:\s$: "{{ pem_passphrase }}"
      .*Common\sName.*: "{{ server_entity_name }}"
  args:
    chdir: "{{ easyrsa_dir }}"
    creates: "{{ easyrsa_dir }}/pki/reqs/{{ server_entity_name }}.req"

- name: sign server's certificate request
  expect:
    command: ./easyrsa sign-req server "{{ server_entity_name }}"
    responses:
      .*Confirm.*:\s$: "yes"
      # note that some of the prompts don't end with whitespace
      # could be changed in a future version
      .*Enter.*ca.key:$: "{{ ca_key_passphrase }}"
  args:
    chdir: "{{ easyrsa_dir }}"
    creates: "{{ easyrsa_dir }}/pki/issued/{{ server_entity_name }}.crt"
...
