---
- name: transfer server config file to the OpenVPN server dir
  template:
    src: server.conf.j2
    dest: "/etc/openvpn/server/server.conf"

# needed by the OpenVPN server
- name: generate Diffie-Hellman parameters file (takes some time)
  command: ./easyrsa gen-dh
  args:
    chdir: "{{ easyrsa_dir }}"
    creates: "{{ easyrsa_dir }}/pki/dh.pem"

- name: archive server config dependencies for transfer
  archive:
    path:
      - "{{ easyrsa_dir }}/pki/ca.crt"
      - "{{ easyrsa_dir }}/pki/issued/{{ server_entity_name }}.crt"
      - "{{ easyrsa_dir }}/pki/private/{{ server_entity_name }}.key"
      - "{{ easyrsa_dir }}/pki/dh.pem"
    dest: "/etc/openvpn/server/config_dependencies.tar.gz"
  register: dependencies

- name: unarchive server config dependencies
  unarchive:
    remote_src: yes
    src: "{{ dependencies.dest }}"
    dest: /etc/openvpn/server

- name: delete dependencies archive
  file:
    path: "{{ dependencies.dest }}"
    state: absent

# needed by OpenVPN to enable TLS authentication
- name: generate static encryption key
  command: openvpn --genkey --secret "./{{ tls_key_name }}.tlsauth"
  args:
    chdir: "/etc/openvpn/server"
    creates: "/etc/openvpn/server/{{ tls_key_name }}.tlsauth"
  notify: "transfer TLS key to client"

- meta: flush_handlers
...
